### ISSUE TITLE
appsettings.json

### ISSUE THREAD

**Issue by solo12zw74** [FedorSharapov/HW7_ConcurrencyImport#1]
https://github.com/FedorSharapov/HW7_ConcurrencyImport/blob/4c3a754007925c4ddf8e4a66f15ba0353071aae2/src/Otus.Teaching.Concurrency.Import.Loader/App.config#L1
Рекомендую посмотреть на 
https://learn.microsoft.com/en-us/iis-administration/configuration/appsettings.json
С ними вроде как легче работать.

**Comment by FedorSharapov** [comment]
Спасибо! Я пробовал в одном из проектов `appsettings.json`. А в этот раз решил попробовать `App.config` =)

**Comment by solo12zw74** [comment]
> Спасибо! Я пробовал в одном из проектов `appsettings.json`. А в этот раз решил попробовать `App.config` =)

На попробовать -  это хорошо. Главное чтобы "старый" подход не стал привычкой. От привычек сложно избавляться.
