### ISSUE TITLE
Don't use GOTO in modern languages

### ISSUE THREAD

**Issue by solo12zw74** [FedorSharapov/HW7_ConcurrencyImport#2]
https://github.com/FedorSharapov/HW7_ConcurrencyImport/blob/4c3a754007925c4ddf8e4a66f15ba0353071aae2/src/Otus.Teaching.Concurrency.Import.Loader/Program.cs#L27

Всем хорошо ваш код, но как только увидел `goto` - аж испугался. Я понимаю, что это работает, но за последние 15 лет в ИТ не видел ни разу такого. Это очень старый подход, рекоменую его избегать.

**Comment by FedorSharapov** [comment]
Это мои временные трудности перехода на C#, т.к. параллельно пишу ПО для микроконтроллеров на си, где это пока что никого не пугает ;)

Внес изменения ad946227df064a6530100af2e6d33c5a794e656d

**Comment by solo12zw74** [comment]
Бывает! )
