### ISSUE TITLE
Pass method parameter in constructor

### ISSUE THREAD

**Issue by solo12zw74** [FedorSharapov/HW7_ConcurrencyImport#3]
https://github.com/FedorSharapov/HW7_ConcurrencyImport/blob/4c3a754007925c4ddf8e4a66f15ba0353071aae2/src/Otus.Teaching.Concurrency.Import.DataAccess/Parsers/CsvParser.cs#L13

Не превый раз вижу в "домашках" передачу **параметров метода в контруктор** класса. Это именно что параметр метода, но не класса. Это неправильно по следюущим причинам:
1. В лишаете себя возможности оегко заиспользовать большинство DI контейнеров
2. Нет никакогологичного оправдания передачи параметра метожа в конструктор класса, чтобы потом заиспользовать его в методе этого класса через глобальную переменную этого класса.

**Comment by FedorSharapov** [comment]
Согласен, спасибо!
Внес изменения 1d150ccca992fc7dc8113c052fc329bda0e7d2ea
