### ISSUE TITLE
lock in helper class

### ISSUE THREAD

**Issue by solo12zw74** [FedorSharapov/HW7_ConcurrencyImport#4]
https://github.com/FedorSharapov/HW7_ConcurrencyImport/blob/4c3a754007925c4ddf8e4a66f15ba0353071aae2/src/Common/ConsoleHelper.cs#L14

Ох что-то стращное и непредсказуемое тут происходит. lock. в статичном классе-хелпере. Может привести к непредсказуемым последствиям, скорее всего в части производительности приложения. Лучше избегать таких критичных моментов в таких "вспомогательных" классах.

**Comment by FedorSharapov** [comment]
В данном случае в нескольких потоках вызывается делегат для отображения сообщения при ошибке сохранения в БД 
https://github.com/FedorSharapov/HW7_ConcurrencyImport/blob/1d150ccca992fc7dc8113c052fc329bda0e7d2ea/src/Otus.Teaching.Concurrency.Import.Loader/Loaders/CustomersDataLoader.cs#L69

который в свою очередь вызывает `ConsoleHelper.WriteLine`
https://github.com/FedorSharapov/HW7_ConcurrencyImport/blob/1d150ccca992fc7dc8113c052fc329bda0e7d2ea/src/Otus.Teaching.Concurrency.Import.Loader/Program.cs#L214-L217

Если не использовать синхронизацию потоков, тогда будет каша в выводе `Console`...
Пока не совсем понимаю как в таком случае действовать...
Не использовать вывод в консоль, а писать ошибки в лог?

**Comment by solo12zw74** [comment]
> Пока не совсем понимаю как в таком случае действовать...
> Не использовать вывод в консоль, а писать ошибки в лог?

К сожалению, опять же, нет единственного "правильного" рещения. Для учбеной задачи - отличное решение. Но для продакшн кода - там вообще вывод в консоль не самая нужная вещь. Потому, что когда программа работает круглосуточно - никто не будет сидеть и смотреть в консоль. А вот парсить логи умеют многие сторонние продукты. И если в логах начинают появлятьс оишбки - можно "подать сигнал".
Вообще говоря, асинхронное/параллельное выполнение программ и запись их состояния в логи - тема нетривиальная. К счастью не приходилось сильно с этим заморачиваться )
Первое, что приходит в голову - дописывать в начало сообщения лога - из какого потока этот лог. Тогда после можно будет отсортировать записи. Но при выводе на консоль , да, отсортировать не получится. В общем в вашем случае это работает - и это главное. Но `lock` это не то решение, которое можно/нужно использовать в каждодневной практике.

**Comment by FedorSharapov** [comment]
Спасибо, за развернутое объяснение! Очень полезная информация для меня!
