### ISSUE TITLE
Use Chunk() method

### ISSUE THREAD

**Issue by solo12zw74** [FedorSharapov/HW7_ConcurrencyImport#5]
https://github.com/FedorSharapov/HW7_ConcurrencyImport/blob/4c3a754007925c4ddf8e4a66f15ba0353071aae2/src/Common/EnumerableExtensions.cs#L8

IEnumerable имеет встроенный метод Chunk. использовать его надёжнее и проще.
https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.chunk?view=net-7.0

**Comment by FedorSharapov** [comment]
Если использовать `Enumerable.Chunk<TSource>(IEnumerable<TSource>, Int32)`, тогда при нечетном входном параметре `size`, например 10005 мы в результате получим на одну часть коллекции больше. Т.е. 2501, 2501, 2501, 2501, 1. И тогда у нас будет использоваться на один поток больше, чем задал пользователь.

У меня получилось следующим образом:
```
public static IEnumerable<IEnumerable<T>> Chunks<T>(this IEnumerable<T> source, int numOfChunk)
{
    var numCustomersPerThread = source.Count() / numOfChunk;
    var remainderCustomers = source.Count() % numOfChunk;

    for (int i = 0; i < numOfChunk; i++)
    {
        var countCustomers = (i != numOfChunk - 1) ? numCustomersPerThread : numCustomersPerThread + remainderCustomers;
        yield return source.Skip(i* numCustomersPerThread).Take(countCustomers);
    }
}
```
И в таком случае результатом будет 2501, 2501, 2501, 2502.     
Но я не уверен что это более правильное решение...   
Что думаете по этому поводу?

**Comment by FedorSharapov** [comment]
Внес изменения в проект: f13998fa227d2d826e20ecf466eb6459d2856e65

**Comment by solo12zw74** [comment]
> Что думаете по этому поводу?

Приветствую. По этому поводу я думаю, что встроенный `Chunk` всё-равно проще и семантически понятней.. Так же он покрыт тестами во фреймворке. А ваш код  - не покрыт. И нуждается в постоянной поддержке.
Реализованный вами алгоритм разбиения коллекции на кусочки - рабочий и быстрый. Но, как говориться, зачем изобретать велосипед, если всё уже придумано за нас. Это всего лишь рекомендация. Чем больше кодовая база, тем меньше хочется иметь в ней вещи не относящиеся к бизнес-логике приложения. Я вот с этой позиции, наверное, говорю.

**Comment by FedorSharapov** [comment]
Да, в ваших словах железная логика и против кода покрытого тестами не поспоришь!)

> Но, как говориться, зачем изобретать велосипед,   

Золотые слова!
