### ISSUE TITLE
Dangerous exception hiding

### ISSUE THREAD

**Issue by solo12zw74** [FedorSharapov/HW7_ConcurrencyImport#6]
https://github.com/FedorSharapov/HW7_ConcurrencyImport/blob/4c3a754007925c4ddf8e4a66f15ba0353071aae2/src/Otus.Teaching.Concurrency.Import.DataAccess/Repositories/CustomerRepository.cs#L29

Вы тут перехватываете исключение, и отдаёте наружу только true/false. Без отладчика никогда не разберётесь в чём именно проблема. Нужно хотя бы логировать детали исключения, чтобы потом было с чем работать.

**Comment by FedorSharapov** [comment]
Спасибо, согласен с вами!  
Добавил логирование ошибок: d69d2e7e0d1de8f0b869784e10a84f8b9f650676
